#!/bin/bash

#check if we are already locked
#this prevents making gestures impossible during lock time
LOCK_STATE=$( awk '{ print }' ~/CONTROL3 )
if [ "$LOCK_STATE" -eq "1" ]
then
exit
fi

#check if we are already running
RUNNING=$( awk '{ print }' ~/CONTROL )
if [ "$RUNNING" -eq "1" ]
then
exit
fi

kdialog --passivepopup "Left Click Mode - Temporary" .01

#signal we are running
echo "1" > ~/CONTROL

#turn off supplemental left click
#this conflicts with natural left click resulting in no clicks
#this lets left click work naturally
#supplemental needed for left clicking during middle click mode
echo "0" > ~/CONTROL2
#turn off third button emulation
xinput --set-prop "ADS7846 Touchscreen" "Evdev Third Button Emulation" 0

sleep 3

#turn back on supplemental left click
echo "1" > ~/CONTROL2
#turn back on third button emulation
xinput --set-prop "ADS7846 Touchscreen" "Evdev Third Button Emulation" 1

#signal we are not running
echo "0" > ~/CONTROL

