#!/bin/bash

#this runs when in xfce only
#start secondary within xfce itself

#set this to 1 if you are running on a model 6
MODEL_6=0

#no left click bug can be fixed by toggling ads7846 in xinput

#waveshare 5 inch
#800 x 480
#display_rotate=1
#axes swap - 1
#axes inversion - 0 1

#waveshare 4 inch
#480 x 800
#no display rotate
#axes swap - 0
#axes inversion - 0 1

#always write FLASH_MODE the first time
FLASH_MODE_MEMORY=-1

#set this here so it is outside the loop - not anymore
#this is bugged - adapter must be undetectable during this time
#PERSISTENT_ADAPTER_CHECK_1=$(lsusb -v | grep Product | grep 340 | wc -l)
#PERSISTENT_ADAPTER_CHECK_2=$(lsusb -v | grep Product | grep 313 | wc -l)
#PERSISTENT_ADAPTER_CHECK_3=$(lsusb -v | grep Product | grep E398 | wc -l)

BOOT_STATUS=$( awk '{ print }' /home/pi/FIRST_BOOT )
if [ "$BOOT_STATUS" -eq "1" ]
then
#temporarily setup touchscreen
xinput set-prop 'ADS7846 Touchscreen' 'Evdev Third Button Emulation' 0
if [ "$MODEL_6" -eq "1" ]
then
xinput set-prop 'ADS7846 Touchscreen' 'Evdev Axes Swap' 0
xinput set-prop 'ADS7846 Touchscreen' 'Evdev Axis Inversion' 0 1
fi
#initial cellular configuration
sudo rm /etc/wvdial.conf
#PROVIDER=$( kdialog --radiolist "Choose your cellular provider:" 1 "ATT" on 2 "ATT Prepaid" off 3 "Tmobile" off )
PROVIDER=$(zenity --list --title="Choose your cellular provider" --column="Providers" ATT "ATT Prepaid" Tmobile)
#if [ "$PROVIDER" -eq 1 ]
if [ "$PROVIDER" = "ATT" ]
then
#att
ADAPTER_CHECK_1=$(lsusb -v | grep Product | grep 340 | wc -l)
if [ $ADAPTER_CHECK_1 -gt 0 ]
then
#continuous programming - used each boot
sudo cp /home/pi/mbim-network.conf.ATT /etc/mbim-network.conf
fi
ADAPTER_CHECK_2=$(lsusb -v | grep Product | grep 313 | wc -l)
if [ $ADAPTER_CHECK_2 -gt 0 ]
then
#initial programming - only used temporarily
#after this the 313 appears to remember the APN in flash
sudo cp /home/pi/wvdial.conf.ATT.313 /etc/wvdial.conf
sudo wvdial&
sleep 3
sudo killall wvdial
fi
ADAPTER_CHECK_3=$(lsusb -v | grep Product | grep E398 | wc -l)
if [ $ADAPTER_CHECK_3 -gt 0 ]
then
#continuous programming - used each boot
sudo cp /home/pi/wvdial.conf.ATT /etc/wvdial.conf
fi
fi
#if [ "$PROVIDER" -eq 2 ]
if [ "$PROVIDER" = "ATT Prepaid" ]
then
#att prepaid
ADAPTER_CHECK_1=$(lsusb -v | grep Product | grep 340 | wc -l)
if [ $ADAPTER_CHECK_1 -gt 0 ]
then
#continuous programming - used each boot
sudo cp /home/pi/mbim-network.conf.ATTPREPAID /etc/mbim-network.conf
fi
ADAPTER_CHECK_2=$(lsusb -v | grep Product | grep 313 | wc -l)
if [ $ADAPTER_CHECK_2 -gt 0 ]
then
#initial programming - only used temporarily
#after this the 313 appears to remember the APN in flash
sudo cp /home/pi/wvdial.conf.ATTPREPAID.313 /etc/wvdial.conf
sudo wvdial&
sleep 3
sudo killall wvdial
fi
ADAPTER_CHECK_3=$(lsusb -v | grep Product | grep E398 | wc -l)
if [ $ADAPTER_CHECK_3 -gt 0 ]
then
#continuous programming - used each boot
sudo cp /home/pi/wvdial.conf.ATTPREPAID /etc/wvdial.conf
fi
fi
#if [ "$PROVIDER" -eq 3 ]
if [ "$PROVIDER" = "Tmobile" ]
then
#tmobile
ADAPTER_CHECK_1=$(lsusb -v | grep Product | grep 340 | wc -l)
if [ $ADAPTER_CHECK_1 -gt 0 ]
then
#continuous programming - used each boot
sudo cp /home/pi/mbim-network.conf.TMOBILE /etc/mbim-network.conf
fi
ADAPTER_CHECK_2=$(lsusb -v | grep Product | grep 313 | wc -l)
if [ $ADAPTER_CHECK_2 -gt 0 ]
then
#initial programming - only used temporarily
#after this the 313 appears to remember the APN in flash
sudo cp /home/pi/wvdial.conf.TMOBILE.313 /etc/wvdial.conf
sudo wvdial&
sleep 3
sudo killall wvdial
fi
ADAPTER_CHECK_3=$(lsusb -v | grep Product | grep E398 | wc -l)
if [ $ADAPTER_CHECK_3 -gt 0 ]
then
#continuous programming - used each boot
sudo cp /home/pi/wvdial.conf.TMOBILE /etc/wvdial.conf
fi
fi
#if kdialog --title "Calibration Check" --warningcontinuecancel "Press Continue to calibrate the touchscreen or Cancel to continue setup"
if zenity --question --text "Press yes to calibrate and no to continue setup"
then
#konsole --noclose -e xinput_calibrator
xfce4-terminal -H -e xinput_calibrator
#kdialog --msgbox "Press OK when calibration is complete"
zenity --info --text="Press OK when calibration is complete"
fi
feh -x -. /home/pi/GESTURES.jpg&
#kdialog --msgbox "Press OK when finished reviewing gestures tutorial"
zenity --info --text="Press OK when finished reviewing gestures tutorials"
echo "0" > /home/pi/FIRST_BOOT
#kdialog --passivepopup "Your system is configured - rebooting" 1
zenity --info --text="Your system is configured - press OK to reboot"
sudo sync
sudo reboot
fi

echo "1" > /home/pi/CONTROL2

CELL_COUNTER=100
EVROUTER_COUNTER=100
WVDIAL_COUNTER=100
DRIVER_COUNTER=100
LEAK_COUNTER=0

(

echo "10"
echo "# Thermal and Energy Management Setup"
#set cpu to max speed when load reaches 95%
#works combined with arm_freq_min=500 in config.txt
#sudo sh -c "echo '95' >> /sys/devices/system/cpu/cpufreq/ondemand/up_threshold"
#disable ethernet - saves 50ma
/home/pi/hub-ctrl.c/hub-ctrl -h 0 -P 1 -p 0
sleep 1

echo "20"
echo "# Touchscreen Setup"
#99-calibration.conf sets up for kde - change below for gtk
#this also sets up hold to right click like on windows
xinput set-prop 'ADS7846 Touchscreen' 'Evdev Third Button Emulation Button' 3
xinput set-prop 'ADS7846 Touchscreen' 'Evdev Third Button Emulation Timeout' 750
xinput set-prop 'ADS7846 Touchscreen' 'Evdev Third Button Emulation' 1
#4 and 5 inch are logically identical so have to specify
if [ "$MODEL_6" -eq "1" ]
then
xinput set-prop 'ADS7846 Touchscreen' 'Evdev Axes Swap' 0
xinput set-prop 'ADS7846 Touchscreen' 'Evdev Axis Inversion' 0 1
fi
xset -dpms
#change below for gtk
#start easystroke for DE independent gesture recognition
easystroke&
sleep 1

echo "30"
echo "# Audio Setup"
amixer -c 0 sset PCM playback 100%
amixer -c 1 sset Mic capture 100%
sleep 1

#may want to run xauth -b and killall xauth
#gammu and modemmanager are similar
#routine to message to 151 if no other workaround for incoming
echo "40"
echo "# SMS Setup"
sudo ModemManager&
sleep 5
sudo cp /home/pi/settings.conf /root/.config/modem-manager-gui/settings.conf
kdesudo modem-manager-gui&
#world readable for sms check-bad idea-can do sudo sh -c instead
sudo chmod -R 777 /root/
CHECKING=1
while [ $CHECKING -gt 0 ]
do
WINDOW_CHECK=`xdotool search --onlyvisible --name Modem | wc -l`
if [ $WINDOW_CHECK -gt 1 ]
then
CHECKING=0
fi
sleep 1
done
sleep 10
#kdialog --passivepopup "Standby - enabling SMS" 1
zenity --notification --window-icon="info" --text "Standby - enabling SMS"&
sleep 1
xvkbd -window Modem* -text "\[Alt]\[a]"
sleep .5
#xvkbd -window Modem* -text "\[Down]"
#change below for gtk
xdotool key Down
sleep .5
xvkbd -window Modem* -text "\[Return]"
sleep .5
xvkbd -window Modem* -text "\[Alt]\[y]"
sleep 1
#xdotool search --onlyvisible --name Modem* windowunmap

echo "50"
echo "# Network Setup"
#initial startup to avoid faulty so and so died messages
#decide what device is being used and set the dialup strategy
ADAPTER_CHECK_1=$(lsusb -v | grep Product | grep 340 | wc -l)
if [ $ADAPTER_CHECK_1 -gt 0 ]
then
sudo mbim-network /dev/cdc-wdm0 start
sleep 2
sudo dhclient wwan0
fi
ADAPTER_CHECK_2=$(lsusb -v | grep Product | grep 313 | wc -l)
if [ $ADAPTER_CHECK_2 -gt 0 ]
then
sudo dhclient wwan0
fi
ADAPTER_CHECK_3=$(lsusb -v | grep Product | grep E398 | wc -l)
if [ $ADAPTER_CHECK_3 -gt 0 ]
then
sudo wvdial&
fi
#change below for gtk
#more touchscreen setup
#sudo rm /tmp/.evrouter\:0
#kdesudo evrouter /dev/input/event*
#stty -F /dev/ttyUSB2 115200 raw -echo -echoe -echok -echoctl -echoke

echo "60"
echo "# Application Startup"
#change below for gtk
#kopete&
pidgin&
linphone&
icedove&

echo "70"
echo "# Miscellaneous Tasks"
#remove to prevent disk space buildup
sudo rm /home/pi/.xsession-errors

)| zenity --progress --title="TEST1" --text="TEST2" --percentage=0

while true
do

#keeps the touchscreen driver running well no matter what
#this fixes touchscreen input failure after sleeping
#disabling irq #505/irq 505 nobody cared
#if [ "$DRIVER_COUNTER" -gt 60 ]
#then
DRIVER_COUNTER=0
DRIVER_CHECK=$(dmesg | grep irq | grep nobody | wc -l)
if [ "$DRIVER_CHECK" -gt "1" ]
then
#kdialog --passivepopup "Touchscreen driver died - taking no action" 1
zenity --notification --window-icon="info" --text "Touchscreen driver died - taking no action"&
#kdialog --passivepopup "Touchscreen driver died - restarting" 1
#sudo modprobe -r ads7846
#sleep 1
#sudo modprobe ads7846
#sleep 1
#sudo killall evrouter
#sleep 5
#dmesg > /home/pi/DMESG_BACKUP
#sudo dmesg -c
fi
#fi

#starts wvdial/kopete/linphone/icedove
#keeps it running no matter what
if [ "$WVDIAL_COUNTER" -gt 30 ]
then
WVDIAL_COUNTER=0
#BURT=$(ps aux | grep wvdial | wc -l)
#if [ "$BURT" -lt 2 ]
#mystery restart fix here and lines below
PERSISTENT_ADAPTER_CHECK_1=$(lsusb -v | grep Product | grep 340 | wc -l)
PERSISTENT_ADAPTER_CHECK_2=$(lsusb -v | grep Product | grep 313 | wc -l)
PERSISTENT_ADAPTER_CHECK_3=$(lsusb -v | grep Product | grep E398 | wc -l)
#maintain 340 connection
if [ $PERSISTENT_ADAPTER_CHECK_1 -gt 0 ]
then
CONNECTION_CHECK=$(sudo ifconfig -a | grep -w inet | wc -l)
if [ $CONNECTION_CHECK -lt 2 ]
then
#kdialog --passivepopup "MBIM died - restarting" 1
zenity --notification --window-icon="info" --text "MBIM died - restarting"&
sudo mbim-network /dev/cdc-wdm0 start
sudo dhclient wwan0
fi
fi
#maintain 313 connection
if [ $PERSISTENT_ADAPTER_CHECK_2 -gt 0 ]
then
CONNECTION_CHECK=$(sudo ifconfig -a | grep -w inet | wc -l)
if [ $CONNECTION_CHECK -lt 2 ]
then
#kdialog --passivepopup "AT based connection died - restarting" 1
zenity --notification --window-icon="info" --text "AT based connection died - restarting"&
sudo wvdial&
sleep 3
sudo killall wvdial
sleep 10
sudo dhclient wwan0
fi
fi
#maintain 303 connection
if [ $PERSISTENT_ADAPTER_CHECK_3 -gt 0 ]
then
if ! ps -C wvdial
then
#kdialog --passivepopup "Wvdial died - restarting" 1
zenity --notification --window-icon="info" --text "WVdial died - restarting"&
sudo wvdial&
fi
fi
#KOPETE_CHECK=$(ps aux | grep kopete | wc -l)
#if [ "$KOPETE_CHECK" -lt 2 ]
#change below for gtk
#if ! ps -C kopete
if ! ps -C pidgin
then
#kdialog --passivepopup "Messaging died - restarting" 1
zenity --notification --window-icon="info" --text "Messaging died - restarting"&
#change below for gtk
#kopete&
pidgin&
fi
#LINPHONE_CHECK=$(ps aux | grep linphone | wc -l)
#if [ "$LINPHONE_CHECK" -lt 2 ]
if ! ps -C linphone
then
#kdialog --passivepopup "Phone died - restarting" 1
zenity --notification --window-icon="info" --text "Phone died - restarting"&
linphone&
fi
#ICEDOVE_CHECK=$(ps aux | grep icedove | wc -l)
#if [ "$ICEDOVE_CHECK" -lt 2 ]
if ! ps -C icedove
then
#kdialog --passivepopup "Email died - restarting" 1
zenity --notification --window-icon="info" --text "Email died - restarting"&
icedove&
fi
fi

#change below for gtk
#starts evrouter and keeps it running no matter what
#if [ "$EVROUTER_COUNTER" -gt 3 ]
#then
#EVROUTER_COUNTER=0
#URT=$(ps aux | grep evrouter | wc -l)
##if [ "$URT" -lt 2 ]
#if ! ps -C evrouter
#then
#kdialog --passivepopup "Evrouter died - Restarting" 1
#sudo rm /tmp/.evrouter\:0
#kdesudo evrouter /dev/input/event*
#fi
#fi

#sends an AT query to the cellular device for signal
#a delay here causes the secondary not to catch the signal
#if [ "$CELL_COUNTER" -gt 15 ]
#then
#CELL_COUNTER=0
#disabled for new signal strength routine
#sudo echo -e -n 'AT+CSQ\r' > /dev/ttyUSB2
#fi

#this number must correspond with xfce notification timeout
if [ "$CELL_COUNTER" -gt 4 ]
then
CELL_COUNTER=0
#query modemmananger for signal
RESULTANT_1=`mmcli -m 0 --simple-status | grep signal`
#check number of unread messages
RESULTANT_2=`cat /root/.local/share/modem-manager-gui/devices/*/sms.gdbm | grep -a '<read>0' | wc -l`
#read linphone history for missed calls
#alternate - show more call detail but less number of calls
#RESULTANT_3=`cat /home/pi/.linphonerc | grep -A1 status=2 | grep from`
RESULTANT_3=`cat /home/pi/.linphonerc | grep -A1 status=2 | grep from | cut -d ":" -f2 | cut -c1-10`
#compute FLASH_MODE for notification light
FLASH_MODE=0
if [ $RESULTANT_2 -gt 0 ]
then
echo "Debug 1"
FLASH_MODE=$(($FLASH_MODE+1))
fi
if [ ! -z $RESULTANT_3 ]
then
echo "Debug 2"
FLASH_MODE=$(($FLASH_MODE+1))
fi
SECURE_BLINKING=$( awk '{ print }' /home/pi/SECURE_BLINKING )
if [ "$SECURE_BLINKING" -eq "1" ]
then
echo "Debug 3"
FLASH_MODE=$(($FLASH_MODE+1))
fi
#set flash mode for notification light
if [ $FLASH_MODE -ne $FLASH_MODE_MEMORY ]
then
echo $FLASH_MODE > /home/pi/FLASH_MODE
fi
FLASH_MODE_MEMORY=$FLASH_MODE
#display convenience popup
#kdialog --passivepopup "$RESULTANT_1/Unread SMS:$RESULTANT_2/Missed Calls:$RESULTANT_3" 1
LOCK_STATUS=$( awk '{ print }' /home/pi/LOCK_STATUS )
if [ $LOCK_STATUS -lt 1 ]
then
killall zenity
if zenity --notification --window-icon="question" --text "$RESULTANT_1/Unread SMS:$RESULTANT_2/Missed Calls:$RESULTANT_3"
then
echo 1 > /home/pi/MOVE_NOTIFICATION
fi&
fi
MOVE_NOTIFICATION=$( awk '{ print }' /home/pi/MOVE_NOTIFICATION )
if [ $MOVE_NOTIFICATION -gt 0 ]
then
echo 0 > /home/pi/MOVE_NOTIFICATION
#get current notification location
QUERY=$(xfconf-query --channel xfce4-notifyd --property /notify-location)
#compute new notification location
QUERY=$(($QUERY+1))
if [ $QUERY -gt 3 ]
then
QUERY=0
fi
#set new notification location
xfconf-query --channel xfce4-notifyd --property /notify-location --set $QUERY
fi
#signal MESSAGE_RECEIVER to start
MESSAGE_RECEIVER_SIGNAL=$( awk '{ print }' /home/pi/MESSAGE_RECEIVER_SIGNAL )
if [ "$MESSAGE_RECEIVER_SIGNAL" -eq "1" ]
then
echo 0 > /home/pi/MESSAGE_RECEIVER_SIGNAL
/home/pi/MESSAGE_RECEIVER&
fi
fi

#deal with memory leaks - every day for the panel
if [ "$LEAK_COUNTER" -gt 86400 ]
then
zenity --notification --window-icon="info" --text "Panel Restart"&
killall xfce4-panel
xfce4-panel&
LEAK_COUNTER=0
fi

#try to avoid double clicks with onscreen keyboard
#cannot detect when plasma keyboard is raised
#can detect other regular on screen keyboard types
#instead just use a dedicated (left) mode when inputting text
#xprop | grep TYPE | grep OVERRIDE - was closest
#but this interfered with kde gestures
#xprop -root _NET_ACTIVE_WINDOW - failed
#wmctl -a :ACTIVE: -v - failed
#xdotool getactivewindow getwindowname - failed

CELL_COUNTER=$(($CELL_COUNTER+1))
#change below for gtk
#EVROUTER_COUNTER=$(($EVROUTER_COUNTER+1))
WVDIAL_COUNTER=$(($WVDIAL_COUNTER+1))
DRIVER_COUNTER=$(($DRIVER_COUNTER+1))
LEAK_COUNTER=$(($LEAK_COUNTER+1))
sleep 1

done

