#!/bin/bash

#no left click bug can be fixed by toggling ads7846 in xinput

#there are three basic modes
#these modes are activated by kde gestures and menu icons
#left click mode, right click mode, web (middle click) mode
#left click is the basic functionality which is usually default
#right click allows 3 seconds for a simulated right click
#web is the default and allows for kinetic scrolling in all apps

#start secondary within kde itself

#device specific
#display_rotate=1
#axes swap - 1
#axes inversion - 0 1

BOOT_STATUS=$( awk '{ print }' /home/pi/FIRST_BOOT )
if [ "$BOOT_STATUS" -eq "1" ]
then
#temporarily setup touchscreen
xinput set-prop 'ADS7846 Touchscreen' 'Evdev Third Button Emulation' 0
#initial cellular configuration
sudo rm /etc/wvdial.conf
PROVIDER=$( kdialog --radiolist "Choose your cellular provider:" 1 "ATT" on 2 "ATT Prepaid" off 3 "Tmobile" off )
if [ "$PROVIDER" -eq 1 ]
then
sudo cp /home/pi/wvdial.conf.ATT /etc/wvdial.conf
fi
if [ "$PROVIDER" -eq 2 ]
then
sudo cp /home/pi/wvdial.conf.ATTPREPAID /etc/wvdial.conf
fi
if [ "$PROVIDER" -eq 3 ]
then
sudo cp /home/pi/wvdial.conf.TMOBILE /etc/wvdial.conf
fi
if kdialog --title "Calibration Check" --warningcontinuecancel "Press Continue to calibrate the touchscreen or Cancel to continue setup"
then
konsole --noclose -e xinput_calibrator
kdialog --msgbox "Press OK when calibration is complete"
fi
feh -x -. /home/pi/GESTURES.jpg&
kdialog --msgbox "Press OK when finished reviewing gestures tutorial"
echo "0" > /home/pi/FIRST_BOOT
kdialog --passivepopup "Your system is configured - rebooting" 1
sudo sync
sudo reboot
fi

echo "1" > /home/pi/CONTROL2

#CELL_COUNTER=100
EVROUTER_COUNTER=100
WVDIAL_COUNTER=100
DRIVER_COUNTER=100

#thermal and energy management section - disabled
#set cpu to max speed when load reaches 95%
#works combined with arm_freq_min=500 in config.txt
#sudo sh -c "echo '95' >> /sys/devices/system/cpu/cpufreq/ondemand/up_threshold"

URT=`kdialog --progressbar "Touchscreen Setup" 4`
#xinput set-prop 'ADS7846 Touchscreen' 'Evdev Axes Swap' 1
#xinput set-prop 'ADS7846 Touchscreen' 'Evdev Axis Inversion' 0 1
xset -dpms
sleep 2
qdbus $URT Set "" value 1

qdbus $URT setLabelText "Audio Setup"
amixer -c 0 sset PCM playback 100%
amixer -c 1 sset Mic capture 100%
sleep 2
qdbus $URT Set "" value 2

#may want to run xauth -b and killall xauth
#gammu and modemmanager are similar
#routine to message to 151 if no other workaround for incoming
qdbus $URT setLabelText "SMS Setup"
sudo ModemManager&
sleep 5
sudo cp /home/pi/settings.conf /root/.config/modem-manager-gui/settings.conf
kdesudo modem-manager-gui&
#world readable for sms check-bad idea-can do sudo sh -c instead
sudo chmod -R 777 /root/
CHECKING=1
while [ $CHECKING -gt 0 ]
do
WINDOW_CHECK=`xdotool search --onlyvisible --name Modem | wc -l`
if [ $WINDOW_CHECK -gt 1 ]
then
CHECKING=0
fi
sleep 1
done
sleep 10
kdialog --passivepopup "Debug Cue - Action" 1
xvkbd -window Modem* -text "\[Alt]\[a]"
sleep .5
xvkbd -window Modem* -text "\[Down]"
sleep .5
xvkbd -window Modem* -text "\[Return]"
sleep .5
xvkbd -window Modem* -text "\[Alt]\[y]"
sleep 3
#xdotool search --onlyvisible --name Modem* windowunmap
qdbus $URT Set "" value 3

qdbus $URT setLabelText "Network Setup"
#initial startup to avoid faulty so and so died messages
sudo wvdial&
sudo rm /tmp/.evrouter\:0
kdesudo evrouter /dev/input/event*
qdbus $URT Set "" value 4
#stty -F /dev/ttyUSB2 115200 raw -echo -echoe -echok -echoctl -echoke

qdbus $URT setLabelText "Application Startup"
kopete&
linphone&
icedove&
qdbus $URT Set "" value 5

while true
do

#keeps the touchscreen driver running well no matter what
#this fixes touchscreen input failure after sleeping
#disabling irq #505/irq 505 nobody cared
#if [ "$DRIVER_COUNTER" -gt 60 ]
#then
DRIVER_COUNTER=0
DRIVER_CHECK=$(dmesg | grep irq | grep nobody | wc -l)
if [ "$DRIVER_CHECK" -gt "1" ]
then
kdialog --passivepopup "Touchscreen driver died - taking no action" 1
#kdialog --passivepopup "Touchscreen driver died - restarting" 1
#sudo modprobe -r ads7846
#sleep 1
#sudo modprobe ads7846
#sleep 1
#sudo killall evrouter
#sleep 5
#dmesg > /home/pi/DMESG_BACKUP
#sudo dmesg -c
fi
#fi

#starts wvdial/kopete/linphone/icedove
#keeps it running no matter what
if [ "$WVDIAL_COUNTER" -gt 15 ]
then
WVDIAL_COUNTER=0
#BURT=$(ps aux | grep wvdial | wc -l)
#if [ "$BURT" -lt 2 ]
#mystery restart fix here and lines below
if ! ps -C wvdial
then
kdialog --passivepopup "Wvdial died - Restarting" 1
sudo wvdial&
fi
#KOPETE_CHECK=$(ps aux | grep kopete | wc -l)
#if [ "$KOPETE_CHECK" -lt 2 ]
if ! ps -C kopete
then
kdialog --passivepopup "Messaging died - Restarting" 1
kopete&
fi
#LINPHONE_CHECK=$(ps aux | grep linphone | wc -l)
#if [ "$LINPHONE_CHECK" -lt 2 ]
if ! ps -C linphone
then
kdialog --passivepopup "Phone died - Restarting" 1
linphone&
fi
#ICEDOVE_CHECK=$(ps aux | grep icedove | wc -l)
#if [ "$ICEDOVE_CHECK" -lt 2 ]
if ! ps -C icedove
then
kdialog --passivepopup "Email died - Restarting" 1
icedove&
fi
fi

#starts evrouter and keeps it running no matter what
if [ "$EVROUTER_COUNTER" -gt 3 ]
then
EVROUTER_COUNTER=0
#URT=$(ps aux | grep evrouter | wc -l)
#if [ "$URT" -lt 2 ]
if ! ps -C evrouter
then
kdialog --passivepopup "Evrouter died - Restarting" 1
sudo rm /tmp/.evrouter\:0
kdesudo evrouter /dev/input/event*
fi
fi

#sends an AT query to the cellular device for signal
#a delay here causes the secondary not to catch the signal
#if [ "$CELL_COUNTER" -gt 15 ]
#then
#CELL_COUNTER=0
#disabled for new signal strength routine
#sudo echo -e -n 'AT+CSQ\r' > /dev/ttyUSB2
#fi

if [ "$CELL_COUNTER" -gt 55 ]
then
CELL_COUNTER=0
#query modemmananger for signal
RESULTANT_1=`mmcli -m 0 --simple-status | grep signal`
#check number of unread messages
RESULTANT_2=`cat /root/.local/share/modem-manager-gui/devices/*/sms.gdbm | grep -a '<read>0' | wc -l`
#display convenience popup
kdialog --passivepopup "$RESULTANT_1/Unread SMS:$RESULTANT_2" 1
fi

#try to avoid double clicks with onscreen keyboard
#cannot detect when plasma keyboard is raised
#can detect other regular on screen keyboard types
#instead just use a dedicated (left) mode when inputting text
#xprop | grep TYPE | grep OVERRIDE - was closest
#but this interfered with kde gestures
#xprop -root _NET_ACTIVE_WINDOW - failed
#wmctl -a :ACTIVE: -v - failed
#xdotool getactivewindow getwindowname - failed

CELL_COUNTER=$(($CELL_COUNTER+1))
EVROUTER_COUNTER=$(($EVROUTER_COUNTER+1))
WVDIAL_COUNTER=$(($WVDIAL_COUNTER+1))
DRIVER_COUNTER=$(($DRIVER_COUNTER+1))
sleep 1

done

