#!/bin/bash

#needed because the touchscreen cannot raise program from tray

#should always choose to close instead of minimize to tray
#should set kde to skip taskbar
#this will hide the program when minimized
#the tray icon should still show new messages
#to switch back just run the icon associated with this script

#if ! ps -C modem-manager-gui
if ! ps -C modem-manager-g
then
echo "Starting"
sudo -E modem-manager-gui
else
echo "Switching"
#the #@ operates on all returned elements instead of first
xdotool search --all "Modem" windowactivate %@
fi

