#!/bin/bash

#launch OSK if not already running

#check if running
#some configurations have a 15 character limit
#if ps -C matchbox-keyboard
#if ps -C matchbox-keyboa
if ps -C xvkbd
then
#if running then kill
#killall matchbox-keyboard
killall xvkbd
#killall devilspie
exit
fi

#launch if not
xvkbd -compact&
#matchbox-keybmatchbox-keyboardoard
#this removes windows decorations aka the title bar
#a ds file must be configured for devilspie to work
#devilspie&

