#!/bin/bash

#check if we are already running
RUNNING=$( awk '{ print }' ~/CONTROL )
if [ "$RUNNING" -eq "1" ]
then
exit
fi

#check if browser is running
#BROWSER_CHECK=$(ps aux | grep qupzilla | wc -l)

#signal we are running
echo "1" > ~/CONTROL

#newest modified - right click mode should always be temporary
xinput --set-prop "ADS7846 Touchscreen" "Evdev Third Button Emulation Button" 3
sleep 3
xinput --set-prop "ADS7846 Touchscreen" "Evdev Third Button Emulation Button" 2

#newest - switch emulation mode to button 3
#xinput --set-prop "ADS7846 Touchscreen" "Evdev Third Button Emulation Button" 3

#if browser running do temporary switch only
#if [ "$BROWSER_CHECK" -gt 1 ]
#then
#kdialog --passivepopup "Right Click Mode - Temporary" .01
#sleep 3
#xinput --set-prop "ADS7846 Touchscreen" "Evdev Third Button Emulation Button" 2
#fi

#if browser not running do permanent switch
#if [ "$BROWSER_CHECK" -lt 2 ]
#then
#kdialog --passivepopup "Right Click Mode - Permanent" .01
#fi

#signal we are not running
echo "0" > ~/CONTROL

