#!/bin/bash

#check if we are already locked
#this stops a menu from popping up during lock time
LOCK_STATE=$( awk '{ print }' ~/CONTROL3 )
if [ "$LOCK_STATE" -eq "1" ]
then
exit
fi

#check if we are already running
RUNNING=$( awk '{ print }' ~/CONTROL )
if [ "$RUNNING" -eq "1" ]
then
exit
fi

kdialog --passivepopup "Right Click Mode - Temporary" .01

#signal we are running
echo "1" > ~/CONTROL

#switch emulation to third button which is right click
xinput --set-prop "ADS7846 Touchscreen" "Evdev Third Button Emulation Button" 3

sleep 3

#switch emulation back to second button which is middle click
xinput --set-prop "ADS7846 Touchscreen" "Evdev Third Button Emulation Button" 2

#signal we are not running
echo "0" > ~/CONTROL

