#!/bin/bash

#edited for i2s audio

#read current volume
#VOLUME_LEVEL=$(amixer | grep dB | cut -d '%' -f1 | cut -d'[' -f2)
VOLUME_LEVEL=$(amixer | grep 'Front Right:' | cut -d '%' -f1 | cut -d'[' -f2)
#if less than 50 then set to clamor
if [ $VOLUME_LEVEL -lt 50 ]
then
#zenity --notification --window-icon="info" --text "Clamor Mode"&
kdialog --passivepopup "Clamor Mode" 1
#amixer -c 0 sset PCM playback 100%
amixer -c 2 sset toot playback 100%
exit
fi
#if greater than or equal to 50 then set to silent
if [ $VOLUME_LEVEL -ge 50 ]
then
#zenity --notification --window-icon="info" --text "Silence Mode"&
kdialog --passivepopup "Silence Mode" 1
#amixer -c 0 sset PCM playback 0%
amixer -c 2 sset toot playback 0%
exit
fi

