#!/bin/bash

#only meant for volume control in standalone mode
#turn the receiver or tv up for volume control in external mode

CHOICE=$( kdialog --radiolist "Volume Control" 1 "Clamor" off 2 "Standard" off 3 "Silence" off )

if [ "$CHOICE" -eq 1 ]
then
cp /home/pi/asoundrc.STANDALONE_CLAMOR /home/pi/.asoundrc
fi

if [ "$CHOICE" -eq 2 ]
then
cp /home/pi/asoundrc.STANDALONE_STANDARD /home/pi/.asoundrc
fi

if [ "$CHOICE" -eq 3 ]
then
cp /home/pi/asoundrc.STANDALONE_SILENCE /home/pi/.asoundrc
fi

